- Importing Pandas and Numpy libraries to use them

In [2]:
import numpy as np 
import pandas as pd

- Using NumPy Arrays (ndarrays) to convert a normal list to a n dimensional array

In [3]:
list1 = [1,2,3,4]

array1 = np.array(list1)
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
list2 =  [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


- looping trough an array without using for loop

In [5]:
print(array2 - 1)

[[0 1 2]
 [3 4 5]]


- NumPy has arrays as its a core system, pandas has series. the only diffrence is pandas have an index

In [6]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)
print(type(series1))

0    13
1    25
2    19
dtype: int32
<class 'pandas.core.series.Series'>


In [7]:
# Create a Series using a NumPy array of ages but customize the indices to be the names that correspond to each age
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)


Emma      13
Swetha    25
Serajh    19
dtype: int32


- One DataFrame can contain many different types of data types, but within a column, everything has to be the same data type

In [8]:
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])
print(dataf)

         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51


- changing 0,1,2 indexes with another column

In [9]:
dataf.set_index("name")

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51

- Let's create a Dataframe

In [11]:
df1 = pd.DataFrame({
    'name': ['John Smith', 'Jane Doe', 'Joe Schmo'],
    'address': ['123 Main St.', '456 Maple Ave.', '789 Broadway'],
    'age': [34, 28, 51]
})
print(df1)

         name         address  age
0  John Smith    123 Main St.   34
1    Jane Doe  456 Maple Ave.   28
2   Joe Schmo    789 Broadway   51


- Another dataframe

In [12]:
df2 = pd.DataFrame({
    'product_ID': [1, 2, 3, 4],
    'product_Name': ['t-shirt', 't-shirt', 'skirt', 'skirt'],
    'color': ['blue', 'green', 'red', 'black']
})
print(df2)

   product_ID product_Name  color
0           1      t-shirt   blue
1           2      t-shirt  green
2           3        skirt    red
3           4        skirt  black
