- Importing Pandas and Numpy libraries to use them

In [28]:
import numpy as np 
import pandas as pd

- Using NumPy Arrays (ndarrays) to convert a normal list to a n dimensional array

In [29]:
list1 = [1,2,3,4]

array1 = np.array(list1)
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [30]:
list2 =  [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


- looping trough an array without using for loop

In [31]:
print(array2 - 1)

[[0 1 2]
 [3 4 5]]


- NumPy has arrays as its a core system, pandas has series. the only diffrence is pandas have an index

In [32]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)
print(type(series1))

0    13
1    25
2    19
dtype: int32
<class 'pandas.core.series.Series'>


In [33]:
# Create a Series using a NumPy array of ages but customize the indices to be the names that correspond to each age
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)


Emma      13
Swetha    25
Serajh    19
dtype: int32


- One DataFrame can contain many different types of data types, but within a column, everything has to be the same data type

In [34]:
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])
print(dataf)

         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51


- changing 0,1,2 indexes with another column

In [35]:
dataf.set_index("name")

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51

- Let's create a Dataframe

In [36]:
df1 = pd.DataFrame({
    'name': ['John Smith', 'Jane Doe', 'Joe Schmo'],
    'address': ['123 Main St.', '456 Maple Ave.', '789 Broadway'],
    'age': [34, 28, 51]
})
print(df1)

         name         address  age
0  John Smith    123 Main St.   34
1    Jane Doe  456 Maple Ave.   28
2   Joe Schmo    789 Broadway   51


- Another dataframe

In [37]:
df2 = pd.DataFrame({
    'product_ID': [1, 2, 3, 4],
    'product_Name': ['t-shirt', 't-shirt', 'skirt', 'skirt'],
    'color': ['blue', 'green', 'red', 'black']
})
print(df2)

   product_ID product_Name  color
0           1      t-shirt   blue
1           2      t-shirt  green
2           3        skirt    red
3           4        skirt  black


- You’re running a chain of pita shops called Pita Power. You want to create a DataFrame with information on your different store locations.

In [38]:
df_pita_shops = pd.DataFrame([
    [1,"Nottingham", 100],
    [2, "Birmingham", 120],
    [3, "Liverpool", 90],
    [4, "London", 115],
],
    columns = ["Store ID", "Location", "Number of Employees"]
)
print(df_pita_shops)

   Store ID    Location  Number of Employees
0         1  Nottingham                  100
1         2  Birmingham                  120
2         3   Liverpool                   90
3         4      London                  115


In [39]:
df_pita_shops.tail(1)

Store ID Location  Number of Employees
3         4   London                  115

In [40]:
df_pita_shops.head(1)

Store ID    Location  Number of Employees
0         1  Nottingham                  100

In [41]:
df_pita_shops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Store ID             4 non-null      int64 
 1   Location             4 non-null      object
 2   Number of Employees  4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


- Selecting any column to showcase all the content of it

In [42]:
df_pita_shops["Location"]

0    Nottingham
1    Birmingham
2     Liverpool
3        London
Name: Location, dtype: object

In [43]:
location = df_pita_shops.Location

In [44]:
print(location)

0    Nottingham
1    Birmingham
2     Liverpool
3        London
Name: Location, dtype: object


In [45]:
print(df_pita_shops)

   Store ID    Location  Number of Employees
0         1  Nottingham                  100
1         2  Birmingham                  120
2         3   Liverpool                   90
3         4      London                  115


- adding a column to our df

In [46]:
df_pita_shops["Area Code"] = ["Ng", "Bir", "Liv", "Lon"]

In [47]:
df_pita_shops

Store ID    Location  Number of Employees Area Code
0         1  Nottingham                  100        Ng
1         2  Birmingham                  120       Bir
2         3   Liverpool                   90       Liv
3         4      London                  115       Lon

- we have this hardware store dataframe that we want to add a column

In [48]:
df = pd.DataFrame([
  [1, '3 inch screw', 0.5, 0.75],
  [2, '2 inch nail', 0.10, 0.25],
  [3, 'hammer', 3.00, 5.50],
  [4, 'screwdriver', 2.50, 3.00]
],
  columns=['Product ID', 'Description', 'Cost to Manufacture', 'Price']
)


- Adding Sold in bulk column

In [49]:
df["Sold in Bulk?"] = ["Yes", "Yes", "No", "No"]
print(df)

   Product ID   Description  Cost to Manufacture  Price Sold in Bulk?
0           1  3 inch screw                  0.5   0.75           Yes
1           2   2 inch nail                  0.1   0.25           Yes
2           3        hammer                  3.0   5.50            No
3           4   screwdriver                  2.5   3.00            No


- adding another column called tax

In [50]:
df["Is taxed?"] = "Yes"
print(df)

   Product ID   Description  Cost to Manufacture  Price Sold in Bulk?  \
0           1  3 inch screw                  0.5   0.75           Yes   
1           2   2 inch nail                  0.1   0.25           Yes   
2           3        hammer                  3.0   5.50            No   
3           4   screwdriver                  2.5   3.00            No   

  Is taxed?  
0       Yes  
1       Yes  
2       Yes  
3       Yes  


- let's add the Sales Tax by mutiplying the price by * 0.075 (7.5%)

In [52]:
df["Sales Tax"] = df.Price* 0.075
# df["Sales Tax"] = df[Price] * 0.075
print(df)

   Product ID   Description  Cost to Manufacture  Price Sold in Bulk?  \
0           1  3 inch screw                  0.5   0.75           Yes   
1           2   2 inch nail                  0.1   0.25           Yes   
2           3        hammer                  3.0   5.50            No   
3           4   screwdriver                  2.5   3.00            No   

  Is taxed?  Sales Tax  
0       Yes    0.05625  
1       Yes    0.01875  
2       Yes    0.41250  
3       Yes    0.22500  


- Add a column to df called 'Margin', which is equal to the difference between the Price and the Cost to Manufacture.

In [53]:
df["Margin"] = df.Price - df["Cost to Manufacture"]
print(df)

   Product ID   Description  Cost to Manufacture  Price Sold in Bulk?  \
0           1  3 inch screw                  0.5   0.75           Yes   
1           2   2 inch nail                  0.1   0.25           Yes   
2           3        hammer                  3.0   5.50            No   
3           4   screwdriver                  2.5   3.00            No   

  Is taxed?  Sales Tax  Margin  
0       Yes    0.05625    0.25  
1       Yes    0.01875    0.15  
2       Yes    0.41250    2.50  
3       Yes    0.22500    0.50  


- using .upper and .lower on a column

In [54]:
df["Description"].apply(str.upper) 

0    3 INCH SCREW
1     2 INCH NAIL
2          HAMMER
3     SCREWDRIVER
Name: Description, dtype: object

In [55]:
df["Description"].apply(str.lower) 

0    3 inch screw
1     2 inch nail
2          hammer
3     screwdriver
Name: Description, dtype: object

- You are managing the webpage of a somewhat violent video game and you want to check that each user’s age is 13 or greater when they visit the site.

- Write a lambda function that takes an inputted age and either returns Welcome to BattleCity! if the user is 13 or older or You must be 13 or older if they are younger than 13. Your lambda function should be called mylambda.

In [56]:
mylambda = lambda age : "Welcome to BattleCity!" if age >= 13 else "You must be 13 or older"
print(mylambda(13))

Welcome to BattleCity!
